### ISSUE TITLE
Document permissions

### ISSUE THREAD

**Issue by flying-sheep** [cargo-bins/release-pr#109]
In the example workflow, I see

```yaml
permissions:
  id-token: write # Enable OIDC
  pull-requests: write
  contents: write
```

and

```yaml
github-token: ${{ secrets.GITHUB_TOKEN }}
```

Yet nothing tells me what the token is for and which scopes it is supposed to have.

When I run the workflow, I get

```
Error: GitHub Actions is not permitted to create or approve pull requests.
```

so apparently it doesn’t use the `pull-requests: write` permission? Why?
