### ISSUE TITLE
pr-label doesn't apply label

### ISSUE THREAD

**Issue by antifuchs** [cargo-bins/release-pr#112]
I invoke the action similar to the template given in the readme, like so:

```yaml
      - uses: cargo-bins/release-pr@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          check-semver: true
          pr-label: "release"
          pr-draft: true
```

But when it creates a PR, the label isn't applied (but the "draft" status is). Is this some limitation in GH actions/api that I'm running into, or is this a bug?

**Comment by passcod** [comment]
Yeah, we ran into this with cargo-binstall and I wasn't able to resolve it for there, was very confused at the time.

**Comment by antifuchs** [comment]
Glad to hear I'm not the only one! Here's the workaround I came up with:

```yaml
      - uses: cargo-bins/release-pr@v2
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          check-semver: true
      - uses: actions-ecosystem/action-regex-match@v2
        id: pr-id
        with:
          text: ${{ steps.pr.outputs.pr-url }}
          regex: "/pull/([0-9]+)$"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: release
          number: ${{ steps.pr-id.outputs.group1 }}
```

In a way, it composes more nicely, but it would be neater to not have to regex-munge the PR URL (instead, get the number from the action's outputs directly).
